---
- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  run_once: true

- name: "Delete anonymous MySQL server user for {{ ansible_hostname }}"
  mysql_user: check_implicit_admin=yes login_user=root login_password="{{ mysql_root_password }}" user="" host="{{ ansible_hostname }}" state="absent"
  notify: restart-mariadb
  run_once: true

- name: Delete anonymous MySQL server user for localhost
  mysql_user: check_implicit_admin=yes login_user=root login_password="{{ mysql_root_password }}" user="" state="absent"
  notify: restart-mariadb
  run_once: true

- name: Set MySQL root password
  mysql_user: check_implicit_admin=yes login_user=root login_password="{{ mysql_root_password }}" user=root password="{{ mysql_root_password }}"
  notify: restart-mariadb
  run_once: true

- name: Remove the MySQL test database
  mysql_db: login_user=root login_password="{{ mysql_root_password }}" db=test state=absent
  notify: restart-mariadb
  run_once: true
