---
- name: Get OpenStack-Ansible
  git:
    repo=https://github.com/openstack/openstack-ansible.git
    dest=/opt/openstack-ansible

- name: Install required pkgs
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - ntp
      - ntpdate
      - openssh-server
      - python-devel
      - bridge-utils 
      - iputils 
      - lsof 
      - lvm2
      - tcpdump

- name: Ensure OpenStack config directory exists
  file: path=/etc/openstack_deploy state=directory mode=0755

- name: Copy base OpenStack config directory
  command: cp -R /opt/openstack-ansible/etc/openstack_deploy /etc

- template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'openstack_user_config.yml', dest: '/etc/openstack_deploy/openstack_user_config.yml' }
    - { src: 'user_variables.yml', dest: '/etc/openstack_deploy/user_variables.yml' }

- name: Run boostrap-ansible
  command: sudo bash /opt/openstack-ansible/scripts/bootstrap-ansible.sh 

- name: Generate user_secrets.yml
  shell: scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
  args:
    chdir: /opt/openstack-ansible


